#pragma once

#include <string>

#include <iostream>

/**
 * Data for the files to be generated by podmate app
 **/
struct OutputFileParameters {
    std::string headerFileName; //<! name of the header file to be generated
    std::string sourceFileName; //<! name of the source file to be generated

    std::string headerPreamble; //<! string will be written after #pragma once, but before the source code
    std::string sourcePreamble; //<! string will be written at the top of the generated source file

    friend bool operator==(OutputFileParameters const&, OutputFileParameters const&);
    friend bool operator!=(OutputFileParameters const&, OutputFileParameters const&);
    friend std::ostream& operator<<(std::ostream&, OutputFileParameters const&);
};


